package Model;

public enum BuffType {
    DISARM,
    STUN,
    POWER,
    HOLY,
    COMBO,
    WEAKNESS,
    WHITE_WALKER_WOLF,
    POISON,
    POSITIVE_DISPEL,
    HIT_POWER,
    HEALTH_POWER,
    HIT_WEAKNESS,
    HEALTH_WEAKNESS,
    CHAMPION,
    LION_ROAR,
    BWITCH,
    JEN_JOON,
    ON_DEATH_WEAKNESS,
    HOLY_WEAKNESS,
    ON_SPAWN_WEAKNESS,
    NEGATIVE_DISARM,
    NEGATIVE_POISON
}
